#!/usr/bin/env python3
"""Rebuild offline paper burned-area ladder (Models C, D, E) and optional fFire.

Paper versions (see paper/paper.typ / paper-typst.pdf):
  Model C  global formula, aggregate ILAMB fit
  Model D  same form, spatial / active-fire objective
  Model E  per-continent params + fuel amplitude + seasonal transform
  fFire E  combustion with per-continent betas on Model E BA

Figures for the manuscript live under paper/figures/ (hand-authored paper panels).
They are not regenerated by this script.

Usage:
  python scripts/reproduce_paper.py
  python scripts/reproduce_paper.py --skip-ffire
  python scripts/reproduce_paper.py --holdout
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PY = sys.executable


def run(cmd, env=None):
    print("\n==>", " ".join(cmd) if isinstance(cmd, list) else cmd)
    e = os.environ.copy()
    if env:
        e.update(env)
    subprocess.check_call(cmd, cwd=REPO, env=e)


def check_drivers():
    need = [
        REPO / "data/crujra/dbar_monthly.npy",
        REPO / "data/crujra/p_ann_monthly.npy",
        REPO / "data/crujra/p_month_monthly.npy",
        REPO / "data/crujra/t_air_monthly.npy",
        REPO / "global_baseline_modelC_inputs_1997-2016.nc",
        REPO / "models/paper/C.json",
        REPO / "models/paper/D.json",
        REPO / "models/paper/E/assembly.json",
    ]
    missing = []
    for p in need:
        if not p.exists():
            try:
                missing.append(str(p.relative_to(REPO)))
            except ValueError:
                missing.append(str(p))
    if missing:
        raise SystemExit(
            "Missing required inputs:\n  - "
            + "\n  - ".join(missing)
            + "\n\nSee docs/setup.md and scripts/download_inputs.sh."
        )


def main():
    ap = argparse.ArgumentParser(description="Reproduce paper Models C/D/E (+ optional fFire)")
    ap.add_argument("--skip-ffire", action="store_true")
    ap.add_argument(
        "--holdout",
        action="store_true",
        help="Also build held-out year/cell E variants and run validators",
    )
    args = ap.parse_args()

    check_drivers()

    # Model C: aggregate fit, legacy annual->monthly transform
    run(
        [
            PY,
            "scripts/reproduce_modelC.py",
            "--params",
            "models/paper/C.json",
            "--out",
            "ilamb/MODELS/paper/Model-C",
            "--seasonal-transform",
            "0",
            "--title",
            "Model C (global, aggregate ILAMB fit)",
        ]
    )

    # Model D
    run(
        [
            PY,
            "scripts/reproduce_modelC.py",
            "--params",
            "models/paper/D.json",
            "--out",
            "ilamb/MODELS/paper/Model-D",
            "--seasonal-transform",
            "1",
            "--title",
            "Model D (spatial / active-fire objective)",
        ]
    )

    # Model E: continental assembly
    run(
        [PY, "scripts/assemble_continental.py"],
        env={"SEASONAL_TRANSFORM": "1", "ASSEMBLY": "best"},
    )

    if args.holdout:
        run(
            [PY, "scripts/assemble_continental.py"],
            env={"SEASONAL_TRANSFORM": "1", "ASSEMBLY": "ho"},
        )
        run(
            [PY, "scripts/assemble_continental.py"],
            env={"SEASONAL_TRANSFORM": "1", "ASSEMBLY": "cell"},
        )
        if (REPO / "scripts/validate_holdout.py").is_file():
            run([PY, "scripts/validate_holdout.py"])
        if (REPO / "scripts/validate_holdout_cells.py").is_file():
            run([PY, "scripts/validate_holdout_cells.py"])

    if not args.skip_ffire:
        fuel = REPO / "global_baseline_modelCfuel_inputs_1997-2016.nc"
        csoil = REPO / "data/trendy_v14/EDv3_S3_cSoil.nc"
        if not fuel.is_file() or not csoil.is_file():
            print(
                "[warn] skipping fFire: need global_baseline_modelCfuel_inputs_1997-2016.nc "
                "and data/trendy_v14/EDv3_S3_cSoil.nc"
            )
        else:
            run(
                [PY, "scripts/assemble_combustion_continental.py"],
                env={"BA_MODEL": "Model-E"},
            )

    print("\nDone.")
    print("  BA:    ilamb/MODELS/paper/Model-{C,D,E}/burntArea.nc")
    print("  fFire: ilamb/MODELS/paper/Model-E-fFire/fFire.nc")
    print("  figs:  paper/figures/  (static paper panels; not regenerated here)")
    print("  typst: cd paper && typst compile paper.typ paper-typst.pdf")


if __name__ == "__main__":
    main()
